# Generated by Django 3.0 on 2021-04-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='level',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='office',
            name='location',
            field=models.CharField(max_length=50),
        ),
    ]
