# Generated by Django 3.0 on 2021-04-15 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offc', '0002_auto_20210407_2121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='office',
            old_name='name',
            new_name='nam',
        ),
    ]
