# Generated by Django 3.0 on 2021-04-15 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offc', '0003_auto_20210415_1246'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='office',
            new_name='ofice',
        ),
    ]
