# Generated by Django 3.0 on 2021-04-15 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offc', '0004_auto_20210415_1303'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ado',
            new_name='adoo',
        ),
    ]
