# Generated by Django 3.0 on 2021-04-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offc', '0005_auto_20210415_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoo',
            name='create_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
