# Generated by Django 3.0 on 2021-04-17 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0003_products_create_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='update_product_price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.IntegerField()),
                ('new_price', models.IntegerField()),
                ('create_at', models.DateTimeField()),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prod.products')),
            ],
        ),
    ]
